spring:  
  application:
    name: product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/auth/realms/myriad/protocol/openid-connect/certs
          user-name-attribute: preferred_username
  
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
       
management:
  security:
    enabled: false
  health:
    consul:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
